"""One policy source, projected into reports and the README policy block.

These are reviewed qualification decisions, not conclusions inferred from a
dataset's self-declaration. Projection tests prevent drift, not policy mistakes.
"""


def qualification_policy() -> dict:
    # Return a fresh tree: no report may mutate the policy for another run.
    return {
        "policy_id": "selected_sample_diagnostic_v1",
        "statistics_status": "DIAGNOSTIC_ONLY",
        "statistics_notice": "the statistics below are NOT findings.",
        "claims": {
            "selected_sample_statistics": {
                "status": "DIAGNOSTIC_ONLY",
                "reason": "describes_this_run_not_market_wide_evidence",
            },
            "market_wide_anomaly_survival": {
                "status": "NOT_EVIDENCE",
                "reason": "historical_membership_outcomes_and_research_gates_not_validated",
                "label": "Market-wide anomaly survival",
                "notice": "no survival rate claimed.",
            },
        },
    }


def qualification_lines(evidence: dict) -> list[str]:
    claim = evidence["claims"]["market_wide_anomaly_survival"]
    return [
        f"EVIDENCE: {evidence['statistics_status']} -- {evidence['statistics_notice']}",
        f"{claim['label']}: {claim['status']}; {claim['notice']}",
    ]


def readme_qualification(policy: dict | None = None) -> str:
    lines = qualification_lines(qualification_policy() if policy is None else policy)
    return "\n".join([
        "<!-- qualification:begin; generated by fza.qualification -->",
        *["> " + line for line in lines],
        "<!-- qualification:end -->",
    ])


if __name__ == "__main__":
    print(readme_qualification())
