"""Project reviewed, scoped examples from one archive; not a research validator.

Tests catch drift in numbers, source fields and the reviewed wording together.
They cannot establish that the underlying methodology or interpretation is true.
Changing the selected archive or the interpretation requires renewed review.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ARCHIVE = "examples/outputs/b_selected_200_rerun_20260909/demo_run.json"
BEGIN = "<!-- diagnostic-examples:begin; generated by scripts/readme_examples.py -->"
END = "<!-- diagnostic-examples:end -->"


def require(condition, message):
    if not condition:
        raise ValueError("README example requires review: " + message)


def examples(bundle):
    comparison = bundle["vintage_comparisons"]["asset_growth"]
    layers = comparison["detail"]["layers"]
    original, common = layers["original-process"], layers["common-observation"]
    require(bundle["evidence"]["statistics_status"] == "DIAGNOSTIC_ONLY", "qualification")
    for layer in (original, common):
        require(layer["status"] == "DIAGNOSTIC_ONLY", "layer status")
        require(layer["outcome_identity"]["status"] == "MATCHED", "label/holding-period identity")
    require(original["sample"]["scoring_scope"] ==
            "ARM_SPECIFIC_OBSERVATIONS_ON_SHARED_DATES", "original scoring scope")
    require(common["sample"]["scoring_scope"] == "COMMON_OBSERVATION_KEYS", "common keys")
    require(common["sample"]["identical_observation_keys"] is True, "key equality")
    require(common["sample"]["cleaning_scope"] == "ARM_SPECIFIC_INPUT_KEYS", "cleaning scope")
    require(original["ic_gap"] > 0 > common["ic_gap"], "sign reversal")
    require(comparison["diagnostic_verdict"].startswith("FAIL:"), "original verdict")
    require(comparison["detail"]["threshold_kind"] ==
            "PRECONFIGURED_DIAGNOSTIC_NOT_SIGNIFICANCE_TEST", "threshold meaning")

    gates = bundle["research_gates"]
    unresolved = {"historical_membership_completeness", "terminal_outcomes"}
    absent = {"post_publication_out_of_sample", "multiple_testing",
              "free_baseline", "trading_costs"}
    require(set(gates) == unresolved | absent, "gate inventory")
    require(all(gates[k]["status"] == "UNRESOLVED" for k in unresolved), "unresolved gates")
    require(all(gates[k]["status"] == "NOT_IMPLEMENTED" for k in absent), "unimplemented gates")
    trap = bundle["factors"]["roe"]["naive_trap"]
    require(trap["n_dates_exposed"] == trap["n_signal_dates"] > 0, "date-level trap scope")
    require(trap["exposure_rate"] == 1.0, "date-level exposure rate")

    return "\n".join([
        BEGIN,
        "### What the diagnostics show",
        "",
        f"Examples from the [archived {bundle['data_summary']['securities']}-company run]"
        f"({ARCHIVE});",
        "these describe that selected sample, not market-wide anomaly survival.",
        "",
        "- **Comparison scope changes the interpretation.** For `asset_growth`, the",
        f"  restated-minus-PIT IC gap is `{original['ic_gap']:+.4f}` in the original process and",
        f"  `{common['ic_gap']:+.4f}` when scoring common `(date, ticker)` observations. Upstream",
        "  cleaning remains arm-specific. We do not interpret the original gap as a",
        '  "restatement advantage": this is sensitivity, not a pure sample-effect',
        "  decomposition. The original diagnostic FAIL remains; the common-observation",
        "  result is DIAGNOSTIC_ONLY, not a replacement PASS or a significance test.",
        "- **Evidence limits remain explicit.** Historical membership and terminal",
        f"  outcomes are the {len(unresolved)} UNRESOLVED gates; post-publication out-of-sample,",
        f"  multiple testing, free baseline and trading costs are {len(absent)} "
        "NOT_IMPLEMENTED gates.",
        "  UNRESOLVED is not a measured bias size; NOT_IMPLEMENTED is not passed.",
        "- **Naive-query exposure is measured by date.** For `roe`, on",
        f"  {trap['n_dates_exposed']}/{trap['n_signal_dates']} checked signal dates, "
        "at least one future-filed record would be",
        "  available to the naive query. This does not mean all rows are future-filed",
        "  or that the PIT pipeline leaked.",
        END,
    ])


def validate_readme(document, bundle):
    require(document.count(BEGIN) == document.count(END) == 1, "unique example block")
    actual = document[document.index(BEGIN):document.index(END) + len(END)]
    require(actual == examples(bundle), "numbers, source link or scoped wording drifted")


if __name__ == "__main__":
    print(examples(json.loads((ROOT / ARCHIVE).read_text(encoding="utf-8"))))
